webserver:
  build: docker/webserver
  ports:
    - "80:80"
    - "443:443"
  links:
    - websocketserver
websocketserver:
  build: docker/websocketserver
  ports:
    - "2794:2794"
  volumes:
    - ${PWD}/simple_server:/code
  command: cargo run --verbose
